ALIEN_ANIMATION_COUNTDOWN = 20

MAP_WIDTH = 1000
MAP_HEIGHT = 1000

ALIEN_WIDTH = 35
ALIEN_HEIGHT = 25
ALIEN_SPEED = 1

PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50
PLAYER_SPEED = 3
PLAYER_SHOT_COOLDOWN = 30

ROCKET_WIDTH = 5
ROCKET_HEIGHT = 15
ROCKET_SPEED = 6 # if it's from player, then * 2

WALL_WIDTH = 25
WALL_HEIGHT = 25

LAST_RESORT_LINE = 850
